server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/member?zeroDateTimeBehavior=convertToNull&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: root
    password: Zk@041916
    driver-class-name: com.mysql.jdbc.Driver

