server:
  port: 88

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: youtube_route
          uri: https://www.youtube.com
          predicates:
            - Query=url,youtube

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/