server:
  port: 8080

spring:
  application:
    name: ecommerce-coupon
  datasource:
    url: jdbc:mysql://localhost:3306/coupon?zeroDateTimeBehavior=convertToNull&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: root
    password: Zk@041916
    driver-class-name: com.mysql.jdbc.Driver


